name: Bug report
description: Something isn't working correctly
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please fill out the sections below so we can reproduce and fix it.

  - type: input
    id: version
    attributes:
      label: xanax version
      placeholder: "0.2.0"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python version
      placeholder: "3.12.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal code that triggers the bug.
      render: python
      placeholder: |
        from xanax import Xanax, SearchParams

        client = Xanax(api_key="...")
        # ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: traceback
    attributes:
      label: Traceback / error output
      render: text
      description: Paste any error output here.
